### ISSUE TITLE
Node 4.2 triggers change on file open

### ISSUE THREAD

**Issue by nerijusgood** [kimmobrunfeldt/chokidar-cli#17] opened 2015-10-26 13:29 UTC
Hi,

Recently updated node to 4.2.1 and whenever I run task with chokidar it triggers `change` on every single touch to file: it is enough to open file to trigger change. 

Same package.json works perfect with Node 0.12.7.

Example script:

```
"watch:sg-styles": "chokidar 'styleguide/styles/**/*.css' -c 'npm run build:sg-styles'",
```

**Comment by kimmobrunfeldt** [comment] 2015-10-26 13:42
This CLI is a wrapper for [chokidar](https://github.com/paulmillr/chokidar) library. Can you reproduce the issue when directly calling chokidar lib like this:

```
var chokidar = require('chokidar');

var watcher = chokidar.watch(['styleguide/styles/**/*.css']);
watcher.on('all', function(event, path) {
    console.log(event, path)
});
```

If yes, please file an issue to the chokidar library.

**Comment by nerijusgood** [comment] 2015-10-27 17:44
Hi,

I have tried just chokidar and it seems to work just fine. It could be my project - there is nodemon watching for app changes and chokidar for styling and assets. It is quite complicated task composition, but weird thing that it works perfect on Node V0.12.7 and not on Node V4.2.1.

**Comment by kimmobrunfeldt** [comment] 2015-10-29 09:33
Ok thanks for reporting. That's indeed weird, I'll try this myself at some point.

**Comment by nerijusgood** [comment] 2015-10-29 09:39
Thanks. Ill try to create example case this weekend to share:)

**Comment by te-online** [comment] 2016-01-29 12:03
Unfortunately, I experience exactly the same problem after changing to node v 4.2.6 from 0.12.7.

My task in package.json looks like that
```JSON
chokidar 'scripts/**/*.js' -c 'npm run dev:build:scripts'
```

If I open a file in a text editor it is already detected as a change, if I close it without saving it happens again. Standalone version of chokidar works as expected. Using chokidar-cli 1.2.0.

**Comment by heikkipora** [comment] 2018-08-30 17:05
I'm doing a bit of cleaning here and closing this issue because of its age. If this issue is still relevant to you and can be reproduced with the newest release (v1.2.1), please do update and re-open it.

**Closed by heikkipora** 2018-08-30 17:05 UTC
